### PR TITLE
Refactored Cron tasks (Batch processing, queries in repository)

### PR DESCRIPTION
**Pull request by VladMartyshevskyi**
1) Added batch processing for notifications
2) Refactored changeStatus method. Now it selects only necessary notifications.
3) Refactored NotificationRepository - changed existing query and added new one.

### CODE REVIEW

**Review by kolya-mazurok2 — CHANGES_REQUESTED** [review]
Why query hardcoded? Rest are looking fine.

**Comment by VladMartyshevskyi** [comment]
The query is hardcoded becouse it should be constant and never change. That query selects all notifications for processing (e.g NEW or IN_PROCESS that was changed no later than specified time)
But don't merge this branch. Some changes are required. I will notify you, when the branch is ready for merge.

**Comment by kolya-mazurok2** [comment]
ok

**Comment by VladMartyshevskyi** [comment]
I've added batch processing using ThreadPoolTaskExecutor. Fixed a bug when the same batch of notification is taken by different threads (added time offset for processing).
Renamed SheduledTask to NotificationHandler.

**Pull request merged**
